---
- name: Update user password on multiple servers
  hosts: all  #
  become: yes 
  gather_facts: true
 
  tasks:
    - name: user password is updated
      user:
        name: "{{ user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always   
